name: scrum_poker
description: Scrum Poker

version: 1.0.9+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  wakelock:
    git:
      url: git://github.com/aafanasev/wakelock.git
  shared_preferences: 0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: false
  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf
