name: Screenshots & Web

on: 
  push:
    branches: 
      - master
    paths:
      - 'lib/**'
      - 'web/**'

jobs:
  screenshots:
    runs-on: macos

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
        cmd: ./tools/generate_screenshots.sh phone_
        api: 25
        tag: default
        abi: x86
        hardwareProfile: pixel
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
        cmd: ./tools/generate_screenshots.sh tablet_
        api: 25
        tag: default
        abi: x86
        hardwareProfile: 10.1in WXGA (Tablet)
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        title: Screenshots
        labels: actions, screenshots
        branch: screenshots
        branch-suffix: timestamp
  
  web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: ./tools/build_web.sh
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        title: Web
        labels: actions, web
        branch: web
        branch-suffix: timestamp
