name: Take screenshots

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: macos

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
        cmd: ./tools/take_screenshots.sh
        api: 25
        tag: default
        abi: x86
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
