name: Screenshots & Web

on: 
  push:
    branches: 
      - master
    paths:
      - 'lib/**'
      - 'web/**'

jobs:
  screenshots:
    runs-on: macos

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get
    - run: ./tools/run_test.sh
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.5
    - name: Phone screenshots
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
        cmd: ./tools/take_screenshots.sh phone
        api: 25
        tag: default
        abi: x86
        hardwareProfile: pixel
    - name: Remove previous emulator
      run: $ANDROID_HOME/tools/bin/avdmanager delete avd -n emulator
    - name: Tablet screenshots
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
        cmd: ./tools/take_screenshots.sh tablet
        api: 25
        tag: default
        abi: x86
        hardwareProfile: 34
        cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -skin 1280x800
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        title: Screenshots
        labels: actions, screenshots
        branch: screenshots
        branch-suffix: timestamp
  
  web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: ./tools/build_web.sh
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        title: Web
        labels: actions, web
        branch: web
        branch-suffix: timestamp
